#!/usr/bin/env bash
# Install load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 206031-web-01    54.144.221.209:80 check
    server 206031-web-02 	34.232.69.26:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
