#!/usr/bin/env bash
# This script is displaying "Best School' 10 times using while
count=0
while [ $count -lt 11 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	count=$(( count + 1))
done

