#!/usr/bin/env bash
# This script is to file or not to file
filename="school"
if [ -e "$filename" ]
then
	echo -n "$filename"
	echo " file exists"
	if [ -s "$filename" ]
	then
		echo -n "$filename"
		echo " file is not empty"
	else
		echo -n "$filename"
		echo " file is empty"
	fi
	if [ -f "$filename" ]
	then
		echo -n "$filename"
		echo " is a regular file"
	fi

else
	echo -n "$filename"
	echo " file does not exist"
fi

